#!/bin/bash

path_to_karatechop="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $path_to_karatechop
. "$path_to_karatechop/karatechop_functions"


## Scan args, set variables.
while [ "$1" ]
do
	case $1 in
		-c|--chop)
			karate_mode="chop"
			shift
			;;
		-d|--input-dir)
			shift
			if [[ ! -d $1 ]]; then
				echo "-i $1: Not a valid directory."
				exit 1
			fi
			input_dir="$1"
			shift
			;;
		-i|--input-file)
			shift
			if [[ ! -f $1 || "$1" == "" ]]; then
				echo "-i $1: Input file not valid."
				exit 1
			fi
			input_file="$1"
			shift
			;;
		-o|--output-dir)
			shift
			if [[ ! -d $1 ]]; then
				mkdir $1
			fi
			if [[ ! -d $1 ]]; then
				echo "-o $1: Directory does not exist and could not be created."
				exit 1
			fi
			output_dir=$1
			shift
			;;
		-r|--reassemble)
			karate_mode="reassemble"
			shift
			;;
	esac
done


check_output_dir() {
	if [[ "$output_dir" == "" ]]; then
		output_dir="$(pwd)/karatechop-out"	
	fi
	if [ ! -d "$output_dir" ]; then
		mkdir "$output_dir"
	fi
	if [ ! -d "$output_dir" ]; then
		echo "Could not make output directory $output_dir."
		exit 1
	fi
}

main() {
	if [[ "$karate_mode" == "" ]]; then
		echo "No mode set."
		echo "Usage: karatechop [Mode] [OPTIONS] [FILES]"
		exit 1
	fi

	

	if [[ "$karate_mode" == "chop" ]]; then
		if [[ "$input_file" == "" ]] || [ ! -f "$input_file" ]; then
			echo "No input file set."
			echo "Usage: karatechop -c -i /path/to/input_file.ext"
			exit 1
		fi
		if [[ "$output_dir" == "" ]]; then
			output_dir="$input_file.chop"
		fi
		check_output_dir && \
		karate_chop $input_file $output_dir && \
		exit 0
	fi

	if [[ "$karate_mode" == "reassemble" ]]; then
		if [[ "$input_dir" == "" ]] || [ ! -d "$input_dir" ]; then
			echo "Input directory invalid."
			echo "Usage: karatechop -r -d /path/to/input_dir/"
			exit 1
		fi
		check_output_dir && \
		karate_fix $input_dir $output_dir && \
		exit 0
	fi
	exit 1
}

main
