#!/bin/bash

karate_chop() {
	local target_file=$1
	local dest_dir=$2
	split --unbuffered -d "$target_file" "karate.chop."
	mv karate.chop.* "$dest_dir"
}

karate_fix() {
	local target_dir=$1
	local target_file="$(basename $target_dir)"
	local dest_dir=$2
	cat $target_dir/karate.chop.* > "$target_file"
	mv "$target_file" $dest_dir
	rm $target_dir/karate.chop.*
}
