#!/bin/bash

############################################################
## Chop a large file into a shitload of smaller files
## or reassemble the shitload of smaller files
## into the original larger file.
##########################
#############
######
####
###
#
#
##
#####
######
################
######################

